import { useEffect, useState } from 'react'
import { Link, Navigate, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import LandingPage from './pages/LandingPage'
import ProblemPage from './pages/ProblemPage'
import { CreateListingForm, ListingBrowser } from './features/listings'
import StatusState from './components/StatusState'
import Header from './components/Header'
import { apiErrorMessage, createListing, getCurrentUser, getListings, getMyListings, loginUser, registerUser, reserveListing } from './services/api'
import './App.css'
import './styles/sharebite.css'

const sessionKey = 'sharebite-session'
const storedSession = () => { try { return JSON.parse(localStorage.getItem(sessionKey) || localStorage.getItem('hacka1-session') || 'null') } catch { return null } }
const withId = (listing) => ({ ...listing, id: listing.id || listing._id })

function AuthPage({ session, onSession }) {
  const location = useLocation(); const navigate = useNavigate(); const isRegister = location.pathname === '/register'
  const [form, setForm] = useState({ name: '', email: '', password: '' }); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(false)
  if (session?.user) return <Navigate to="/" replace />
  const submit = async (event) => { event.preventDefault(); setLoading(true); setMessage(''); try { const { data } = await (isRegister ? registerUser(form) : loginUser(form)); onSession(data); navigate(location.state?.from?.pathname || '/') } catch (error) { setMessage(apiErrorMessage(error, 'We could not sign you in.')) } finally { setLoading(false) } }
  return <div className="site-page auth-page"><main className="auth-main shell"><section className="auth-intro"><p className="kicker">ShareBite LK community</p><h1>Good food finds a better next stop.</h1><p>Join local businesses, neighbours, and community groups making safe surplus food easier to share.</p><ul className="auth-benefits"><li>Discover food available nearby</li><li>Reserve in just a few steps</li><li>Share surplus responsibly</li></ul></section><section className="auth-card"><p className="kicker">{isRegister ? 'Get started' : 'Welcome back'}</p><h2>{isRegister ? 'Create your account' : 'Log in to ShareBite'}</h2><p className="subtitle">{isRegister ? 'Register to share or reserve safe surplus food.' : 'Sign in to share food or reserve a listing.'}</p><form onSubmit={submit}>{isRegister && <label>Name<input required minLength="2" autoComplete="name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /></label>}<label>Email<input required type="email" autoComplete="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} /></label><label>Password<input required type="password" minLength="6" autoComplete={isRegister ? 'new-password' : 'current-password'} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} /></label>{message && <p className="error" role="alert">{message}</p>}<button className="primary" disabled={loading}>{loading ? 'Please wait…' : isRegister ? 'Create account' : 'Log in'}</button></form><p className="switch">{isRegister ? 'Already have an account?' : 'New here?'} <button type="button" onClick={() => navigate(isRegister ? '/login' : '/register')}>{isRegister ? 'Log in' : 'Create an account'}</button></p></section></main></div>
}

function ListingsPage({ session, onExpired, onLogout }) {
  const navigate = useNavigate(); const location = useLocation(); const [listings, setListings] = useState([]); const [state, setState] = useState('loading'); const [feedback, setFeedback] = useState(null); const [reservingId, setReservingId] = useState('')
  const load = async () => { setState('loading'); setFeedback(null); try { const { data } = await getListings(); const next = (data.listings || []).map(withId); setListings(next); setState(next.length ? 'ready' : 'empty') } catch (error) { setFeedback({ type: 'error', text: apiErrorMessage(error) }); setState('error') } }
  useEffect(() => { if (session?.token) void Promise.resolve().then(load) }, [session?.token])
  if (!session?.token) return <Navigate to="/login" replace state={{ from: location }} />
  const reserve = async (listing) => { if (reservingId) return; setReservingId(listing.id); setFeedback(null); try { const { data } = await reserveListing(listing.id, session.token); const updated = withId(data.listing); setListings((current) => current.map((item) => item.id === updated.id ? updated : item)); setFeedback({ type: 'success', text: `Reserved “${updated.title}”. Please collect it before the listed time.` }) } catch (error) { if (error.response?.status === 401) { onExpired(); navigate('/login', { state: { from: location } }); return } setFeedback({ type: 'error', text: apiErrorMessage(error, 'We could not reserve this listing.') }) } finally { setReservingId('') } }
  return <div className="site-page"><Header user={session.user} onLogout={onLogout} /><main className="listing-page shell"><p className="kicker">Available nearby</p><h1>Find food to collect</h1><p className="listing-intro">Browse safe surplus food shared by local businesses and reserve what you can collect on time.</p>{feedback && state !== 'error' && <StatusState type={feedback.type}>{feedback.text}</StatusState>}{state === 'loading' && <StatusState type="loading" />}{state === 'error' && <StatusState type="error" action={<button className="retry-button" onClick={load}>Try again</button>}>{feedback?.text}</StatusState>}{state === 'empty' && <StatusState type="empty" />}{state === 'ready' && <ListingBrowser listings={listings} onReserve={reserve} reserveDisabled={Boolean(reservingId)} />}</main></div>
}

function ActivityList({ title, items, empty, link, linkLabel }) { return <article className="activity-list"><h3>{title}<span>{items.length}</span></h3>{items.length ? <ul>{items.map((listing) => <li key={listing.id}><div><strong>{listing.title}</strong><span>{listing.portions} portions · {listing.district}</span></div><em className={`activity-badge ${listing.status}`}>{listing.status}</em></li>)}</ul> : <div className="activity-empty"><p>{empty}</p><Link to={link}>{linkLabel} →</Link></div>}</article> }

function DashboardPage({ session, onLogout }) {
  const [activity, setActivity] = useState({ shared: [], reserved: [] }); const [activityState, setActivityState] = useState('loading')
  useEffect(() => { if (!session?.token) return; getMyListings(session.token).then(({ data }) => { setActivity({ shared: (data.shared || []).map(withId), reserved: (data.reserved || []).map(withId) }); setActivityState('ready') }).catch(() => setActivityState('error')) }, [session?.token])
  if (!session?.token) return <Navigate to="/login" replace state={{ from: { pathname: '/dashboard' } }} />
  const user = session.user || {}; const joined = user.createdAt ? new Date(user.createdAt).toLocaleDateString(undefined, { month: 'long', year: 'numeric' }) : 'ShareBite member'
  return <div className="site-page"><Header user={user} onLogout={onLogout} /><main className="dashboard-page shell"><section className="dashboard-hero"><div className="dashboard-avatar">{user.name?.trim().charAt(0).toUpperCase() || 'U'}</div><div><p className="kicker">Your ShareBite space</p><h1>Welcome, {user.name?.split(' ')[0] || 'neighbour'}.</h1><p>Manage your community food-sharing journey from one place.</p></div></section><section className="dashboard-grid"><article className="profile-details"><p className="kicker">Profile details</p><h2>Your account</h2><dl><div><dt>Full name</dt><dd>{user.name || '—'}</dd></div><div><dt>Email address</dt><dd>{user.email || '—'}</dd></div><div><dt>Member since</dt><dd>{joined}</dd></div></dl></article><article className="dashboard-actions"><p className="kicker">Quick actions</p><h2>Make an impact today</h2><p>Every safe listing and timely collection helps good food go further.</p><div><Link className="button button-primary" to="/share-food">Share food →</Link><Link className="button button-outline" to="/find-food">Find food →</Link></div></article></section><section className="dashboard-activity"><div className="activity-heading"><div><p className="kicker">Your activity</p><h2>Shared and reserved food</h2></div><p>Keep track of food you have offered and food you plan to collect.</p></div>{activityState === 'loading' ? <p className="activity-status">Loading your activity…</p> : activityState === 'error' ? <p className="activity-status">We could not load your activity right now.</p> : <div className="activity-columns"><ActivityList title="Food you shared" items={activity.shared} empty="You have not shared any food yet." link="/share-food" linkLabel="Share food" /><ActivityList title="Food you reserved" items={activity.reserved} empty="You have not reserved any food yet." link="/find-food" linkLabel="Find food" /></div>}</section><section className="dashboard-note"><span>✦</span><div><h2>A thoughtful community starts with you</h2><p>Remember to only share food that is safe to collect and consume before its listed deadline.</p></div></section></main></div>
}

function ShareFoodPage({ session, onExpired, onLogout }) { const navigate = useNavigate(); const location = useLocation(); if (!session?.token) return <Navigate to="/login" replace state={{ from: location }} />; const submit = async (listing) => { try { await createListing(listing, session.token) } catch (error) { if (error.response?.status === 401) { onExpired(); navigate('/login', { state: { from: location } }); throw new Error('Your session has expired. Please log in again.', { cause: error }) } throw new Error(apiErrorMessage(error, 'We could not create this listing.'), { cause: error }) } }; return <div className="site-page"><Header user={session.user} onLogout={onLogout} /><main className="listing-page form-page shell"><p className="kicker">Share safe surplus</p><h1>Post food for your community</h1><p className="listing-intro">Only list food that is safe to collect and consume before the stated deadline.</p><CreateListingForm onSubmit={submit} /></main></div> }

export default function App() { const [session, setSession] = useState(storedSession); const token = session?.token; const save = (next) => { localStorage.setItem(sessionKey, JSON.stringify(next)); setSession(next) }; const logout = () => { localStorage.removeItem(sessionKey); setSession(null) }; useEffect(() => { if (!token) return; getCurrentUser(token).then(({ data }) => { setSession((current) => { const next = { ...current, user: data.user }; localStorage.setItem(sessionKey, JSON.stringify(next)); return next }) }).catch(logout) }, [token]); const shared = { user: session?.user, onLogout: logout }; return <Routes><Route path="/" element={<LandingPage {...shared} />} /><Route path="/find-food" element={<ListingsPage session={session} onExpired={logout} onLogout={logout} />} /><Route path="/share-food" element={<ShareFoodPage session={session} onExpired={logout} onLogout={logout} />} /><Route path="/dashboard" element={<DashboardPage session={session} onLogout={logout} />} /><Route path="/about" element={<ProblemPage {...shared} />} /><Route path="/login" element={<AuthPage session={session} onSession={save} />} /><Route path="/register" element={<AuthPage session={session} onSession={save} />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes> }
